laravel-taiwan/docs

localization.md

translate localization.md

---

helpers.md

translate helpers.md

---

testing.md

translate testing.md

---

events.md

translate events.md

---

collections.md

translate collections.md

---

packages.md

finish to translate packages.md page

finish to translate packages.md page

---

homestead.md

translate homestead.md

---

facades.md

translate facades.md

---

bus.md

Translate bus.md

---

commands.md

translate commands.md

---

packages.md

modify the title of page

---

extending.md

translate extending.md

---

middleware.md

Translate middleware.md

---

container.md

Translated container.md

---

session.md

Translated session.md

---

errors.md

translate errors.md

---

configuration.md
controllers.md
responses.md

幫忙 Review 幾個地方並修正，還請大家幫忙看是否有誤，感恩。

Review configuration.md, controllers.md and responses.md

---

mail.md

replace mail.md title `mail` -> `郵件`

mail.md title

---

artisan.md

translate artisan.md

---

upgrade.md

Translate upgrade.md

---

homestead.md

上一個  #142 pull request 忘記刪除翻譯過的英文句子

Remove english sentence

---

elixir.md

Update translation of elixir.md

---

envoy.md

Update translation of envoy.md

---

artisan.md

補完為翻譯之部分，內文有翻譯不順的地方煩請review，感謝

Update translation of artisan.md

---

packages.md

修正語意不通順處並翻譯未翻譯的部分，麻煩幫忙校對，Thanks！

packages.md 校對潤稿

---

controllers.md

請幫忙 review 控制器（controllers）章節，謝謝。

翻譯 controllers.md

---

homestead.md

翻譯完成 homestead.md

---

lifecycle.md

Please help to review the translation on lifecycle.md, thanks!

Translate lifecycle.md.

---

documentation.md

fix broken link

---

homestead.md

補上官網最新的一個段落「以專案分別安裝 Homestead」

翻譯完成 homestead.md (已更新)

---

mail.md

翻譯了 mail.md，再請幫忙看一下有沒有什麼問題，謝謝。

Translate mail.md.

---

controllers.md

fix controllers.md 07/26 補尚未翻譯的部分。

---

authentication.md

fix authentication.md

---

billing.md

我覺得翻得有點可怕，還沒翻完，先丟上來請有空的人幫忙 review

Translate billing.md(not completed)

---

eloquent-collections.md
eloquent-mutators.md
eloquent-serialization.md

translate eloquent-mutators.md and eloquent-serialization.md

---

session.md

session 翻譯

---

session.md

Reverts laravel-taiwan/docs#221

Revert "session 翻譯"

---

validation.md

之前全文衝突，所以 commit 回原文後重新再翻掉一次
#210 
cc @chentsulin

Translate validation.md

---

database.md

Translate database

---

queries.md

Translate queries

---

authorization.md

Translate authorization

---

requests.md
routing.md

Update requests & routing

---

mail.md
middleware.md

Update mail & middleware

---

quickstart.md

Translate quickstart

---

quickstart-intermediate.md

Translate quickstart-intermediate

---

routing.md

fix routing.md

---

installation.md

Translate installation

---

configuration.md

Translate configuration

---

homestead.md

Translate homestead

---

responses.md

Translate responses

---

views.md

Translate views.md for v5.2

---

routing.md

Translate routing

---

validation.md

[5.1] Update validation.md

---

authorization.md
helpers.md
mail.md

* authorization.md 
* helpers.md 
* mail.md

5.2 solve conflict in authorization.md helpers.md mail.md

---

controllers.md

Translate controller

---

quickstart-intermediate.md

Artisan 建立 Controller 的指令和原文不同，多了 --plain

fix artisan command in quickstart-intermediate.md

---

migrations.md

Fix typo in migrations.md

---

authentication.md

翻譯 5.2 的 authentication.md

---

container.md

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/laravel-taiwan/docs/pull/317%23discussion_r51696563%22%2C%20%22https%3A//github.com/laravel-taiwan/docs/pull/317%23discussion_r51696648%22%2C%20%22https%3A//github.com/laravel-taiwan/docs/pull/317%23discussion_r51697285%22%2C%20%22https%3A//github.com/laravel-taiwan/docs/pull/317%23discussion_r51697286%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%201890b3c2d6dd993ea2dd7720fa49076fd107ef6f%20container.md%2081%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/laravel-taiwan/docs/pull/317%23discussion_r51697286%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cu9019%5Cu88e1%5Cu4e0d%5Cu8a72%5Cu65b7%5Cu884c%22%2C%20%22created_at%22%3A%20%222016-02-03T09%3A34%3A54Z%22%2C%20%22user%22%3A%20%7B%2 …

translate container

---

validation.md

Translate validation

---

eloquent.md

#287
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/laravel-taiwan/docs/pull/306%23discussion_r48395186%22%2C%20%22https%3A//github.com/laravel-taiwan/docs/pull/306%23discussion_r48395198%22%2C%20%22https%3A//github.com/laravel-taiwan/docs/pull/306%23discussion_r48395240%22%2C%20%22https%3A//github.com/laravel-taiwan/docs/pull/306%23discussion_r48396438%22%2C%20%22https%3A//github.com/laravel-taiwan/docs/pull/306%23discussion_r48399726%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%204e86d8b4d56bc8247bc4240dedd31f722ac66ded%20eloquent.md%20644%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/laravel-taiwan/docs/pull/306%23discussion_r48395240%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22local%20%5Cu7ffb%5Cu6210%2A%2A%5Cu5c40%5Cu90e8% …

Translate eloquent.md

---

views.md

翻譯 views.md (v5.5)

---

artisan.md

參考google﹑Laravel CN 和 Laravel.tw，若有翻譯錯誤麻煩請協助修正。

Translate artisan.md (v5.5)

---

contributions.md

Translate contributions.md (v5.5)

---

authorization.md

參考google﹑Laravel CN 和 Laravel.tw，若有翻譯錯誤麻煩請協助修正。

Translate authorization.md (v5.5)

---

configuration.md

參考google﹑Laravel CN 和 Laravel.tw，若有翻譯錯誤麻煩請協助修正。

Translate configuration.md (v5.5)

---

contributing.md

剛剛思考了一下，這個文件好像不需要翻譯，不過內容很短就翻了一下...

Translate contributing.md (v5.5)

---

csrf.md

Translate csrf.md (v5.5)

---

contracts.md

- 99.999% 複製 v5.3 的翻譯內容，僅更新原始文件更新的連結。

Translate contracts.md (v5.5)

---

deployment.md

Translate deployment.md (v5.5)

---

database.md

Translate database.md (v5.5)

---

database-testing.md

1. 工廠狀態那一段原文用了很難翻的單字，所以翻譯可能會有誤。
2. 接下來要翻譯 `dusk.md`，有九百多行...

Translate database-testing.md (v5.5)

---

dusk.md

1. 已同步原始文件最新內容。
2. 內容總計九百多行，不過很多內容重複性很高，所以翻譯難度不高。
3. Text 不知道應該用哪種翻譯，所以保留等修改。
4. 部分 Page 被指涉為類別，所以保留原文。

Translate dusk.md (v5.5)

---

envoy.md

Translate envoy.md (v5.5)

---

errors.md

Translate errors.md (v5.5)

---

events.md

Translate events.md (v5.5)

---

readme.md

Translate readme.md (v5.5)

---

eloquent-collections.md

Translate eloquent-collections.md (v5.5)

---

eloquent-mutators.md

Translate eloquent-mutators.md (v5.5)

---

passwords.md

Translate passwords.md (v5.5)

---

validation.md

1. 把 `pipe delimiters` 翻譯成 `|` 分隔符號
2. `Countable` 是 php 類別，就不翻譯了

翻譯 validation.md

---

providers.md

內容與 `5.3` 完全一樣，所以直接複製 `5.3` 的台灣翻譯

Translate providers.md (v5.5)

---

packages.md

Translate packages.md (v5.5)

---

requests.md

Translate requests.md (v5.5)

---

responses.md

修正 responses.md 翻譯問題

---

helpers.md

修正 helpers.md 翻譯問題

---

structure.md

修正 structure.md 翻譯問題

---

session.md

修正 session.md 翻譯問題

---

mix.md

修正 mix.md 翻譯問題

---

upgrade.md

Translate upgrade.md (v5.5)

---

valet.md

這邊的 `site` 好像可以翻成`網站`，目前暫時翻成`專案`

Translate valet.md (v5.5)

---

releases.md

Translate releases.md (v5.5)

---

notifications.md

Translate 5.5 notification.md

---

filesystem.md

Translate filesystem.md (v5.5)

---

queues.md
redis.md

微調 [5.5] queues.md 翻譯

---

queues.md
redis.md

- Worker 為保留文件原意，統一使用 Queue worker。

Translate 5.5 queues.md

---

homestead.md

1. 已同步原始文件 `12/8` 之前的更新
2. 發現 `5.4` 有人有更新翻譯，不過並不是很完全，但還是大量使用之前的翻譯，並補充新內容。

Translate homestead.md (v5.5)

---

hashing.md

Translate hashing.md (v5.5)

---

urls.md

Translate urls.md (v5.5)

---

lifecycle.md

Translate lifecycle.md (v5.5)

---

frontend.md

Translate frontend.md (v5.5)

---

scout.md

Translate scout.md (v5.5)

---

middleware.md

Translate middleware.md (v5.5)

---

horizon.md

Translate horizon.md (v5.5)

---

localization.md

translation strings 不太確定怎麼翻譯，目前照字面翻成「翻譯字串」

翻譯 localization.md

---

mail.md

翻譯 mail.md

---

testing.md

Translate testing.md (v6.x)

---

testing.md

Translate testing.md (v7.x)
* 新增 Artisan 測試運作

Translate testing.md (v7.x)

---

valet.md

 Translate valet.md (v7.x)

---

views.md

Translate view.md (7.x)
- 大部分的翻譯都是從 `5.5` 搬來的，但有稍微修飾與補充翻譯

Translate view.md (7.x)

---

upgrade.md

Translate upgrade.md（5.6）

---

upgrade.md

Translate `upgrade.md` (5.7)
- 翻譯這個文件的時候發現 `stub` 可以翻成`範本`

Translate upgrade.md (5.7)

---

upgrade.md

Translate upgrade.md (5.8)

---

telescope.md
upgrade.md

Translate upgrade.md (v6.x)

---

upgrade.md

Translate upgrade.md (v8.x)
